### ISSUE TITLE
Add "final step" keyword argument for gmx.workflow.from_tpr

### ISSUE THREAD

**Issue by jmhays** [kassonlab/gmxapi#158]
Currently, `from_tpr` only allows the user to specify the number of steps to _continue_ a run (similar to the nsteps command line argument in Gromacs), i.e., "run for X more steps." It would be useful to be able to specify a _final_ number of steps, i.e., run until X steps have been completed in the total simulation.

**Comment by eirrgang** [comment]
Yes.

Arguably, instead of acting like the ``nsteps`` command line flag, the ``steps`` keyword should define a simulation phase that produces a trajectory ``steps`` time steps long starting from whatever the micro state it receives as input.

But the goal expressed in this issue is clearer and even nearer term, I think.

With a solution to this issue, the user can calculate the final step of their trajectory on their own and override the entry in the TPR file with an explicit integer value. The parameter is forward compatible with the idea for the "next-generation" work specification in that we can add abstraction as it is available to express the final step in terms of another workflow object.

E.g.

    >>> # gmxapi 0.0.6.1
    >>> start_step = 1000 # hard-coded value based on something else
    >>> phase2_num_steps = 1000
    >>> md_phase2 = gmx.workflow.from_tpr(tpr_filename, final_step=start_step + phase2_num_steps)

This sets the last step of the trajectory requested in the input record to 2000. Assuming either tpr_filename has an initial time step number of 1000 or the input data includes an initial checkpoint at step 1000, this gets an additional 1000 steps of trajectory, but the user is responsible for robustly calculating start_step across restarts.

    >>> # gmxapi 0.0.7
    >>> # md_phase1 = ...
    >>> start_step = md_phase1.output.trajectory['timestep'].extract()[-1]
    >>> # possible alternate syntax
    >>> # start_step = md_phase1.output.trajectory['frames'][-1].extract()['timestep']
    >>> phase2_num_steps = 1000
    >>> md_phase2 = gmx.workflow.from_tpr(tpr_filename, final_step=start_step + phase2_num_steps)

This sets the last step of the trajectory requested in the input record to 1000 more than the final step extracted from the output of the previous simulation. Assuming the trajectory from the first phase stops at step 1000, this gets an additional 1000 steps of trajectory, and gmxapi figures out how to get 
the value of start_step.

```
    >>> # gmxapi 0.1
    >>> # md_phase1 = ...
    >>> phase2_num_steps = 1000
    >>> md_phase2 = gmx.workflow.from_tpr(
    ...        tpr_filename,
    ...        final_step=md_phase1.output.trajectory['final_step'] + phase2_num_steps)
```

The calculation of the starting and stopping steps can then be deferred until run time, and gmxapi promises that the output of phase2 is a trajectory segment encompassing 1000 steps starting from the last time step in the trajectory output of phase1.

The syntax in the second example may seem a little bit cumbersome, but it would let us make all three examples forward compatible without introducing intermediate syntax to try to deprecate later. We could skip the 'output' namespace hierarchy and define that to `extract` the `trajectory` output of an md operation implies a data flow condition that trajectory output is complete. However, we might want to keep the explicit naming to distinguish between operations that might consume trajectory frames as data events (with an unknown number of events still to come), versus the const data object that is the result of the md operation once it completes.

I'm also open to other syntax and semantics, but I think I can get the first use case by the end of the week and the second in another week or so. As part of 0.0.7, though, I want to have a utility to read such things from various gmx files, so I don't really expect the syntax in the second example to be used except for illustration.

**Comment by peterkasson** [comment]
I'm not sure about this from a design point of view.
I think the syntax we'd want is similar to -extend for gmx convert-tpr, although this could be "total" extension.
I would argue that giving a *time* (simulation time, not wall-clock) argument is better than giving a *steps* argument.  People get too much into reporting simulation length in steps, when that is essentially an irrelevant parameter for a physical process.

**Comment by peterkasson** [comment]
Talking with Jennifer--I think I understand the issue here.  I am supportive of the overall idea, but I think there are two questions.
1.  Stylistically, I would suggest run_until as a way to phrase this argument instead of final_step.  I think that's clearer and less prone to confusion.
2.  Then there's the question of appropriate units for time:  steps or picoseconds.  Different issue, but I'd support picoseconds.  
(This might be getting way into the weeds, but think about some hypothetical workflow that varied the time step size adaptively.  The consistent time reference is picoseconds.)

**Comment by eirrgang** [comment]
Yes, the use case is on the same lines as ``convert-ptr``. From the user-interface and scientific standpoint, I agree with time versus time step. From both user expectation and implementation perspectives, I think it gets a little trickier, but I'm sure we can figure it out.

``run_until`` seems fine, but given that other use inputs are in numbers of steps, should we be more explicit? If someone provides an integer, we could throw an error, but someone might also enter 1e7 and expect ten million steps... We could make the unit explicit, like some other tools do, with special types, like ``from gmx.units import ps; run_until=1e7*ps``, but that seems more complicated than it needs to be. Maybe ``run_until_time``? Or ``end_time`` or something that might fit well in case we also add a ``start_time`` at some point?

It would be nice if we had a clear and consistent way for a developer to know how many samples and intervals of various lengths would occur in a given time frame or to know a priori how many frames will be in their trajectory, but I don't know that we can solve that problem quickly. It seems like there is some ongoing internal GROMACS discussion on related topics.

One thing we could and probably should do would be to allow the user to programmatically access the actual dt recorded in the input record from which they could make accurate calculations. That is a little bit of a documentation challenge, perhaps, but might be necessary anyway, particularly if we _do_ want to account for varying time step sizes. For instance, ``md.params['dt']`` could produce a series. I'm not sure if we'd want it to optionally produce a series or scalar based on whether the quantity is dynamic or not, but we can easily use some abstraction to make sure that ``md.params['dt'][0]`` is light-weight.

Some of this is getting a bit into the weeds, but is discussion that needs to happen. For the moment, though, it sounds like we agree the requirements of the implementation are clear.

**Comment by peterkasson** [comment]
Let's go with either run_until_time or end_time for now.  (run_until_time is a bit clunky, but it is clear; end_time also ok).  The question of units is interesting because everywhere in the Gromacs interface *outside* of MDP settings (and a few developer flags), ps are time units.  *Inside* MDP settings, units are mostly steps, except for things like thermostat & barostat time constants.  I think encouraging the ps time units for now and leaving the door open to supporting steps in the future is the best move.

**Comment by eirrgang** [comment]
Since the function is called `from_tpr` and not `run_simulation`, `run_until_time` does not seem redundant or overly explicit. `trajectory_time=(start, end)` or some `range`-like syntax might be nice, but that's beyond the scope of the present case.

Arithmetic will be based on the `dt` read from the tpr file, rather than the MDP file or Python interface, so integer arithmetic involving the number of steps should be exact where the same arithmetic could be performed in double-precision floating point without precision errors. I don't think GROMACS can even handle time steps high enough for that to be a problem.

**Comment by eirrgang** [comment]
effectively resolved. continuing work referenced from #187
