### ISSUE TITLE
Using interactive gmx commands such as trjconv within gmxapi

### ISSUE THREAD

**Issue by patriciabrandl** [kassonlab/gmxapi#270]
Hello,
I am new to the gmxapi framework and having big trouble with making the gmx command "trjconv -f file.pdb -s file.pdb -o file.gro"  work in gmxapi as this prompts in the terminal version of gmx the selection of a group. 
While for pdb2gmx I could find the handle  -ff to select the forcefield that is interactively prompted as well, in case it is not specified, I could not find any such thing for the trjconv and am wondering how I can circumvent the issue.
Thanks!

**Comment by eirrgang** [comment]
You can use the *stdin* keyword argument to [commandline_operation](https://manual.gromacs.org/current/gmxapi/userguide/pythonreference.html#gmxapi.commandline_operation) to provide the text input that you would otherwise provide on the command line (as a single string).

Unfortunately, this means that you have to already know what the prompts will be and what the valid choices will be.

Don't forget the line endings. (use `\n` in the string).

I think that use cases involving selections are strong motivation for adding Python bindings to more tools and investing in some user interface improvements. It could help to express interest in such features on the forums, and that would also be a good place for an initial discussion of what the interface should look like. Please share your thoughts at https://gromacs.bioexcel.eu/tag/gmxapi
