### ISSUE TITLE
How to replace coordinates in the simulation input

### ISSUE THREAD

**Issue by chemxyang** [kassonlab/gmxapi#271]
Hello,

I noticed that coordinates in the simulation input can be modified/replaced by using gmxapi.modify_input (https://gitlab.com/gromacs/gromacs/-/issues/3295).
May I ask which parameter shoud be written in gmxapi.modify_input(input, parameters: [dict], label: Optional[[str]= None, context=None)？

Thank you very much!

**Comment by eirrgang** [comment]
Issue [3295](https://gitlab.com/gromacs/gromacs/-/issues/3295) is under development this summer. I hope to have a complete solution in a month or two.

The "related branches" linked from that issue include some prototype / proof-of-concept work, but only expose a low-level interface (at the Python bindings). A high-level interface (`gmxapi.modify_input()`) is not yet available.

Please feel free to comment on [#3295](https://gitlab.com/gromacs/gromacs/-/issues/3295) so that the conversation is not spread across too many forums.
